### ISSUE TITLE
Support Migration Versions for Rails 5.1

### ISSUE THREAD

**Issue by dillonhafer** [jbranchaud/vim-rails-sql-migrations#2]
In Rails 5.1 directly inheriting from ActiveRecord::Migration is not supported. We should specify the Rails release the migration was written for if we are using Rails 5.1:

```ruby
class CreateThings < ActiveRecord::Migration[4.2]
```

**Comment by jbranchaud** [comment]
This has been implemented in #3.

**Comment by dillonhafer** [comment]
This is broken is Rails 5.2 😢
